name: check

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel: [stable, nightly, 1.52.1]

    steps:
    - uses: actions/checkout@v2

    - name: Select Rust channel
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.channel }}
          override: true

    - name: Rust Version Info
      run: |
        rustc --version
        cargo --version

    - name: Test All
      run: cargo test --verbose --all-features
